### PR TITLE
feat: Support ignored testcase reported by Cargo

### PR DESCRIPTION
**Pull request by kingli-crypto**
Why:
- Add support to the `ignored` test case output from `cargo test`
- Report these cases result as `skipped` in junit report

Changes:
- Bump `junit-report` dependency to `0.5.0`
- Add logic to add `Ignored` test cases to testcase set
- Update unittest cases with new expected results

### CODE REVIEW

**Comment by kingli-crypto** [comment]
@johnterickson any chance you can take a look at this pr and consider it?

**Comment by kesselborn** [comment]
@johnterickson could this be merged? It would be very cool to have this in the original code base.

Cheers and thanks for cargo2junit -- very useful :)

**Comment by johnterickson** [comment]
Thanks for the contribution @kingli-crypto and for the poke @kesselborn !

**Comment by johnterickson** [comment]
I'll roll out a 0.1.9

**Comment by kesselborn** [comment]
🎉 cool, thanks a lot

**Pull request merged**
