### PR TITLE
Format the output XML to match GitLab/Jenkins expectations 

### PR DESCRIPTION
**Pull request by johnterickson**
Carrying forward from @sasa-tomic's great start (!) in https://github.com/johnterickson/cargo2junit/pull/37#discussion_r593779049

### CODE REVIEW

**Comment by johnterickson** [comment]
Need to add a few more tests

**Comment by johnterickson** [comment]
@svenstaro you mentioned you'd like to see this ( #37 ) merged.  Is there a particular scenario you would like to test this with before I update the crate?

P.S. Thanks for pointing out the README fix - I'll merge that shortly once I run some tests in this branch.

**Comment by johnterickson** [comment]
@jstarks and @sasa-tomic Any thoughts/concerns before I merge?

**Comment by sasa-tomic** [comment]
LGTM!

**Pull request merged**
